---
- name: Configure Apache.
  lineinfile:
    dest: "{{ apache_config_dir }}/conf/{{ apache_service_name }}.conf"
    state: present
    line: "{{ item.line }}"
    regexp: "{{ item.regexp }}"
  with_items: apache_ports_config
  notify: restart apache

- name: Copy Apache vhost.conf.
  template:
    src: vhosts.conf.j2
    dest: "{{ apache_config_dir }}/conf.d/{{ apache_vhosts_file }}"
    owner: root
    group: root
  notify: restart apache
  when: apache_vhosts_use_template
