---
- name: Configure Apache.
  lineinfile:
    dest: "/etc/httpd/conf/httpd.conf"
    state: present
    line: "{{ item.line }}"
    regexp: "{{ item.regexp }}"
  with_items: apache_ports_config
  notify: restart apache

- name: Copy Apache vhost.conf.
  template:
    src: vhosts.conf.j2
    dest: "/etc/httpd/conf.d/{{ apache_vhosts_file }}"
    owner: root
    group: root
  notify: restart apache
  when: apache_vhosts_use_template
