---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define apache_packages.
  set_fact:
    apache_packages: "{{ __apache_packages | list }}"
  when: apache_packages is not defined

- include: setup-RedHat.yml
  when: ansible_os_family == "RedHat"

- include: configure-RedHat.yml
  when: ansible_os_family == "RedHat"

- name: Ensure Apache has selected state and enabled on boot.
  service:
    name: "{{ apache_daemon }}"
    state: started
    enabled: yes
